version: '3.8'

services:
  postgres:
    env_file:
      - .env.development
    container_name: glasses_postgres_dev
    image: postgres:alpine
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5436:5432"
    volumes:
      - ./.data/db/docker-postgres:/var/lib/postgresql/data
    networks:
      - glasses-client

  app-dev:
    env_file:
      - .env.development
    platform: linux/amd64
    container_name: glasses_dev
    image: "glasses-dev"
    build:
      dockerfile: Dockerfile
      target: app-dev
      context: ./
    ports:
      - "6968:6968"
      - "5050:5050"
    volumes:
      - ./:/app
    networks:
      - glasses-client

networks:
  glasses-client:
