# fly.toml app configuration file generated for skyvisor on 2024-04-25T00:02:00+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'glasses-management-platform'
primary_region = 'lhr'

[build]
  dockerfile = "Dockerfile"
  build-target = "app"

[build.args]
  MODE="production"

[http_service]
  internal_port = 6968
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']


