# fly.toml for Tempo deployment

app = 'glasses-management-platform-tempo'
primary_region = 'lhr'

# Use the official Tempo image
[build]
  image = "grafana/tempo:2.4.1"

# Define how to run Tempo
[processes]
  # Add -server.http-listen-address=0.0.0.0:3200
  app = "-target=all -storage.trace.backend=local -storage.trace.local.path=/data/traces -auth.enabled=false -server.http-listen-address=0.0.0.0:3200"


# Define the HTTP service for the Tempo UI/API
[http_service]
  internal_port = 3200
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]


# Define necessary raw TCP services for Tempo OTLP receivers
[[services]]
  internal_port = 4317
  protocol = "tcp"
  processes = ["app"]
  [[services.ports]]
    port = 4317

[[services]]
  internal_port = 4318
  protocol = "tcp"
  processes = ["app"]
  [[services.ports]]
    port = 4318


# Define the machine resources
[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256


# Mount a persistent volume
[mounts]
  source = "tempo_data"
  destination = "/data"