name: Go CI/CD Pipeline

on:
  push:
    branches:
      - main
      - production

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code from the repo
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Go environment
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21.x'  # Set to the Go version your project uses

      # Cache Go build cache and modules
      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            /go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      # Install dependencies
      - name: Install dependencies
        run: go mod download

      # Run tests
      - name: Run tests
        run: go test -v ./...

      # Build the application
      - name: Build
        run: go build -v ./...

      # Deploy step (only for prod branch)
      - name: Deploy to Production
        if: github.ref == 'refs/heads/prod'
        run: |
          echo "Deploying to production..."
          # Add your deployment script/commands here
